/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Color;
import javax.swing.*;

public class form2 extends javax.swing.JFrame {

    int p, k;
    int p1, p2, p3, p4, p5;

    /**
     * Creates new form form2
     */
    public form2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ahorcado");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ahorcado: Modo Fácil");

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");

        jButton1.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jButton1.setText("Comprobar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jButton2.setText("Comenzar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel3");
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel5.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("jLabel3");

        jLabel6.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel3");

        jTextField4.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Puntaje");

        jLabel8.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton3.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jButton3.setText("Volver a jugar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabel9.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("(Tenés 4 intentos)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(800, 800, 800)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(660, 660, 660)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(830, 830, 830)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(800, 800, 800)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(760, 760, 760)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jButton1)
                .addGap(72, 72, 72)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel8))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel9))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(jLabel6))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(jButton4))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7))
            .addGroup(layout.createSequentialGroup()
                .addGap(505, 505, 505)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(505, 505, 505)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton3))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/1fondo" + ".jpg")));
        jLabel3.setText("");
        jLabel3.setText("");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel8.setText("");
        jButton3.setEnabled(false);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
        jButton1.setEnabled(true);
        jLabel3.setText("D");
        jLabel4.setText("___");
        jLabel5.setText("___");
        jLabel6.setText("___");

        jButton2.setEnabled(false);

    }//GEN-LAST:event_jButton2ActionPerformed
    int gano;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        switch (k) {
            case 0:
                if (jTextField4.getText().equalsIgnoreCase("a")) {
                    jLabel4.setText("A");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("d")) {
                    jLabel5.setText("D");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("o")) {
                    jLabel6.setText("O");
                    jTextField4.setText("");
                } else {
                    jTextField4.setText("");
                    p1++;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/img" + p1 + ".jpg")));

                }

                while (p1 == 4) {

                    JOptionPane.showMessageDialog(null, "Perdiste\nLa palabra era Dado");
                    jLabel3.setText("M");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    k++;
                    p1++;
                    puntaje[0] = 0;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));

                }
                if (jLabel4.getText().equalsIgnoreCase("a") && jLabel5.getText().equalsIgnoreCase("d") && jLabel6.getText().equalsIgnoreCase("o")) {
                    JOptionPane.showMessageDialog(null, "Ganaste");
                    jLabel3.setText("M");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    k++;
                    puntaje[0] = 1;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                }

                break;

            case 1:

                if (jTextField4.getText().equalsIgnoreCase("a")) {
                    jLabel4.setText("A");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("I")) {
                    jLabel5.setText("I");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("Z")) {
                    jLabel6.setText("Z");
                    jTextField4.setText("");
                } else {
                    jTextField4.setText("");
                    p2++;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/img" + p2 + ".jpg")));

                }

                while (p2 == 4) {

                    JOptionPane.showMessageDialog(null, "Perdiste\nLa palabra era Maiz");
                    jLabel3.setText("S");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    k++;
                    p2++;
                    puntaje[1] = 0;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                }
                if (jLabel4.getText().equalsIgnoreCase("a") && jLabel5.getText().equalsIgnoreCase("i") && jLabel6.getText().equalsIgnoreCase("z")) {
                    JOptionPane.showMessageDialog(null, "Ganaste");
                    jLabel3.setText("S");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    k++;
                    puntaje[1] = 1;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                }
                break;
            case 2:
                if (jTextField4.getText().equalsIgnoreCase("e")) {
                    jLabel4.setText("E");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("c")) {
                    jLabel5.setText("C");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("o")) {
                    jLabel6.setText("O");
                    jTextField4.setText("");
                } else {
                    jTextField4.setText("");
                    p3++;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/img" + p3 + ".jpg")));
                }

                while (p3 == 4) {

                    JOptionPane.showMessageDialog(null, "Perdiste\nLa palabra era Seco");
                    jLabel3.setText("V");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    k++;
                    p3++;
                    puntaje[2] = 0;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                }
                if (jLabel4.getText().equalsIgnoreCase("e") && jLabel5.getText().equalsIgnoreCase("c") && jLabel6.getText().equalsIgnoreCase("o")) {
                    JOptionPane.showMessageDialog(null, "Ganaste");
                    jLabel3.setText("V");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    p++;
                    k++;
                    puntaje[2] = 1;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                }
                break;

            case 3:
                if (jTextField4.getText().equalsIgnoreCase("e")) {
                    jLabel4.setText("E");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("n")) {
                    jLabel5.setText("N");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("a")) {
                    jLabel6.setText("A");
                    jTextField4.setText("");
                } else {
                    jTextField4.setText("");
                    p4++;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/img" + p4 + ".jpg")));
                }

                while (p4 == 4) {

                    JOptionPane.showMessageDialog(null, "Perdiste\nLa palabra era Vena");
                    jLabel3.setText("N");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    k++;
                    p4++;
                    puntaje[3] = 0;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));

                }
                if (jLabel4.getText().equalsIgnoreCase("e") && jLabel5.getText().equalsIgnoreCase("n") && jLabel6.getText().equalsIgnoreCase("a")) {
                    JOptionPane.showMessageDialog(null, "Ganaste");
                    jLabel3.setText("N");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    k++;
                    puntaje[3] = 1;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                }
                break;
            case 4:
                if (jTextField4.getText().equalsIgnoreCase("e")) {
                    jLabel4.setText("E");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("x")) {
                    jLabel5.setText("X");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("o")) {
                    jLabel6.setText("O");
                    jTextField4.setText("");
                } else {
                    jTextField4.setText("");
                    p5++;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/img" + p5 + ".jpg")));
                }

                while (p5 == 4) {

                    JOptionPane.showMessageDialog(null, "Perdiste\nLa palabra era Nexo");
                    k++;
                    p5++;

                    puntaje[4] = 0;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                    for (int o = 0; o < puntaje.length; o++) {
                        if (puntaje[o] == 1) {
                            gano++;
                        }
                    }
                }
                if (jLabel4.getText().equalsIgnoreCase("e") && jLabel5.getText().equalsIgnoreCase("x") && jLabel6.getText().equalsIgnoreCase("o")) {
                    JOptionPane.showMessageDialog(null, "Ganaste");

                    k++;
                    puntaje[4] = 1;
                    for (int o = 0; o < puntaje.length; o++) {
                        if (puntaje[o] == 1) {
                            gano++;
                        }
                    }

                }
                break;
        }

        if (k == 5) {
            for (int i = 0; i < puntaje.length; i++) {
                jButton3.setEnabled(true);
                jLabel8.setText(String.valueOf(gano + "/5"));
                jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/1fondo" + ".jpg")));
                 jLabel3.setText("");
                    jLabel4.setText("");
                    jLabel5.setText("");
                    jLabel6.setText("");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        form1 f1 = new form1();
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form2().setVisible(true);
            }
        });
    }

    public static int[] puntaje = new int[5];

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
