/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Color;
import javax.swing.*;

public class form4 extends javax.swing.JFrame {

    int p, k;
    int p1, p2, p3, p4, p5,img;

    /**
     * Creates new form form2
     */
    public form4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ahorcado");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ahorcado: Modo Difícil");

        jLabel3.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");

        jButton1.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jButton1.setText("Comprobar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jButton2.setText("Comenzar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel3");
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel5.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("jLabel3");

        jLabel6.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel3");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Puntaje");

        jLabel8.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton3.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jButton3.setText("Volver a jugar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("jLabel10");
        jLabel10.setPreferredSize(new java.awt.Dimension(56, 23));
        jLabel10.setVerifyInputWhenFocusTarget(false);

        jLabel12.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("jlabel11");
        jLabel12.setPreferredSize(new java.awt.Dimension(56, 23));
        jLabel12.setVerifyInputWhenFocusTarget(false);

        jLabel2.setText("jLabel2");

        jLabel9.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("(Tenés 6 intentos)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(580, 580, 580)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(720, 720, 720)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(800, 800, 800)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(850, 850, 850)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(880, 880, 880)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(850, 850, 850)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addGap(115, 115, 115)
                        .addComponent(jButton2)
                        .addGap(56, 56, 56)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(580, 580, 580)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/1fondo" + ".jpg")));
        
        jButton3.setEnabled(false);
        jButton1.setEnabled(false);
        jLabel3.setText("");
        jLabel3.setText("");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel10.setText("");
        jLabel12.setText("");
        jLabel8.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
        jButton1.setEnabled(true);
        jLabel3.setText("C");
        jLabel4.setText("___");
        jLabel5.setText("___");
        jLabel6.setText("___");
        jLabel10.setText("___");
        jLabel12.setText("___");

        jButton2.setEnabled(false);

    }//GEN-LAST:event_jButton2ActionPerformed
    int gano;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 /** else {
                    jTextField4.setText("");
                    p2++;
                    jLabel9.setIcon(new ImageIcon(getClass().getResource("/imgdificil/img" + p2 + ".jpg")));

                } **/
        switch (k) {
            case 0:
                if (jTextField4.getText().equalsIgnoreCase("a")) {
                    jLabel4.setText("A");
                    jLabel6.setText("A");
                    jLabel10.setText("A");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("b")) {
                    jLabel5.setText("B");
                    jTextField4.setText("");
                }  else if (jTextField4.getText().equalsIgnoreCase("ñ")) {
                    jLabel12.setText("Ñ");
                    jTextField4.setText("");
                } else {
                    jTextField4.setText("");
                    p1++;
                    
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/imgdificil/img" + p1 + ".jpg")));

                }

                while (p1 == 6) {

                    JOptionPane.showMessageDialog(null, "Perdiste\nLa palabra era Cabaña");
                    jLabel3.setText("R");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    jLabel10.setText("___");
                    jLabel12.setText("___");
                    k++;
                    p1++;
                    puntaje[0] = 0;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));

                }
                if (jLabel4.getText().equalsIgnoreCase("a") && jLabel5.getText().equalsIgnoreCase("b") && jLabel6.getText().equalsIgnoreCase("a") && jLabel10.getText().equalsIgnoreCase("a") && jLabel12.getText().equalsIgnoreCase("ñ")) {
                    JOptionPane.showMessageDialog(null, "Ganaste");
                    jLabel3.setText("R");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    jLabel10.setText("___");
                    jLabel12.setText("___");
                    k++;
                    puntaje[0] = 1;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                }

                break;

            case 1:

                if (jTextField4.getText().equalsIgnoreCase("a")) {
                    jLabel4.setText("A");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("b")) {
                    jLabel5.setText("B");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("i")) {
                    jLabel6.setText("I");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("n")) {
                    jLabel12.setText("N");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("o")) {
                    jLabel10.setText("O");
                    jTextField4.setText("");
                } else {
                    jTextField4.setText("");
                    p2++;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/imgdificil/img" + p2 + ".jpg")));

                }



                while (p2 == 6) {

                    JOptionPane.showMessageDialog(null, "Perdiste\nLa palabra era Rabino");
                    jLabel3.setText("Y");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    jLabel10.setText("___");
                    jLabel12.setText("___");
                    k++;
                    p2++;
                    puntaje[1] = 0;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                }
                if (jLabel4.getText().equalsIgnoreCase("a") && jLabel5.getText().equalsIgnoreCase("b") && jLabel6.getText().equalsIgnoreCase("i")&& jLabel10.getText().equalsIgnoreCase("o") && jLabel12.getText().equalsIgnoreCase("n")) {
                    JOptionPane.showMessageDialog(null, "Ganaste");
                    jLabel3.setText("Y");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    jLabel10.setText("___");
                    jLabel12.setText("___");
                    k++;
                    puntaje[1] = 1;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                }
                break;
            case 2:
                if (jTextField4.getText().equalsIgnoreCase("a")) {
                    jLabel4.setText("A");
                    jLabel12.setText("A");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("g")) {
                    jLabel5.setText("G");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("u")) {
                    jLabel6.setText("U");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("r")) {
                    jLabel10.setText("R");
                    jTextField4.setText("");
                } 
                else {
                    jTextField4.setText("");
                    p3++;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/imgdificil/img" + p3 + ".jpg")));
                } 

                while (p3 == 6) {

                    JOptionPane.showMessageDialog(null, "Perdiste\nLa palabra era Yaguar");
                    jLabel3.setText("T");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    jLabel10.setText("___");
                    jLabel12.setText("___");
                    k++;
                    p3++;
                    puntaje[2] = 0;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                }
                if (jLabel4.getText().equalsIgnoreCase("a") && jLabel5.getText().equalsIgnoreCase("g") && jLabel6.getText().equalsIgnoreCase("u")&& jLabel10.getText().equalsIgnoreCase("r") && jLabel12.getText().equalsIgnoreCase("a")) {
                    JOptionPane.showMessageDialog(null, "Ganaste");
                    jLabel3.setText("T");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    jLabel10.setText("___");
                    jLabel12.setText("___");
                    p++;
                    k++;
                    puntaje[2] = 1;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                }
                break;

            case 3:
                if (jTextField4.getText().equalsIgnoreCase("a")) {
                    jLabel4.setText("A");
                    jLabel6.setText("A");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("b")) {
                    jLabel5.setText("B");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("c")) {
                    jLabel12.setText("C");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("o")) {
                    jLabel10.setText("o");
                    jTextField4.setText("");
                 }   
                else {
                    jTextField4.setText("");
                    p4++;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/imgdificil/img" + p4 + ".jpg")));
                }

                while (p4 == 6) {

                    JOptionPane.showMessageDialog(null, "Perdiste\nLa palabra era Tabaco");
                    jLabel3.setText("H");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    jLabel10.setText("___");
                    jLabel12.setText("___");
                    k++;
                    p4++;
                    puntaje[3] = 0;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));

                }
                if (jLabel4.getText().equalsIgnoreCase("a") && jLabel5.getText().equalsIgnoreCase("b") && jLabel6.getText().equalsIgnoreCase("a") && jLabel10.getText().equalsIgnoreCase("o") && jLabel12.getText().equalsIgnoreCase("c")) {
                    JOptionPane.showMessageDialog(null, "Ganaste");
                    jLabel3.setText("H");
                    jLabel4.setText("___");
                    jLabel5.setText("___");
                    jLabel6.setText("___");
                    jLabel10.setText("___");
                    jLabel12.setText("___");
                    k++;
                    puntaje[3] = 1;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                }
                break;
            case 4:
                if (jTextField4.getText().equalsIgnoreCase("o")) {
                    jLabel4.setText("O");
                    jLabel10.setText("O");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("C")) {
                    jLabel5.setText("C");
                    jLabel12.setText("C");
                    jTextField4.setText("");
                } else if (jTextField4.getText().equalsIgnoreCase("I")) {
                    jLabel6.setText("I");
                    jTextField4.setText("");
                }  else if (jTextField4.getText().equalsIgnoreCase("C")) {
                    jLabel6.setText("C");
                    jTextField4.setText("");
                } 
                else {
                    jTextField4.setText("");
                    p5++;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/imgdificil/img" + p5 + ".jpg")));
                }

                while (p5 == 6) {

                    JOptionPane.showMessageDialog(null, "Perdiste\nLa palabra era Hocico");
                    k++;
                    p5++;

                    puntaje[4] = 0;
                    jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/2Horca" + ".jpg")));
                    for (int o = 0; o < puntaje.length; o++) {
                        if (puntaje[o] == 1) {
                            gano++;
                        }
                    }
                }
                if (jLabel4.getText().equalsIgnoreCase("o") && jLabel5.getText().equalsIgnoreCase("c") && jLabel6.getText().equalsIgnoreCase("i") && jLabel10.getText().equalsIgnoreCase("o") && jLabel12.getText().equalsIgnoreCase("c")) {
                    JOptionPane.showMessageDialog(null, "Ganaste");

                    k++;
                    puntaje[4] = 1;
                    for (int o = 0; o < puntaje.length; o++) {
                        if (puntaje[o] == 1) {
                            gano++;
                        }
                    }

                }
                break;
        }

        if (k == 5) {
            for (int i = 0; i < puntaje.length; i++) {
                jButton3.setEnabled(true);
                jLabel8.setText(String.valueOf(gano + "/5"));
                jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/1fondo" + ".jpg")));
                  jLabel3.setText("");
                    jLabel4.setText("");
                    jLabel5.setText("");
                    jLabel6.setText("");
                    jLabel10.setText("");
                    jLabel12.setText("");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        form1 f1 = new form1();
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form4().setVisible(true);
            }
        });
    }

    public static int[] puntaje = new int[5];

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
